info:
  version: @project.version@

spring:
  application:
    name: MONITOR
  boot:
    admin:
      url: http://localhost:${server.port}
      nofify.to: netoht@gmail.com
  mail:
    host: smtp.gmail.com
    port: 465
    properties:
      mail.smtp.ssl.enable: true